### PR TITLE
Upgrade zune-jpeg

### PR DESCRIPTION
**Pull request by fintelia**
Currently targets `0.5.0-rc0`, will switch to the full `0.5.0` release once it comes out

### CODE REVIEW

**Comment by Murad-Awad** [comment]
You need to use ZCursors rather than Cursor from what I can tell, did some testing and when decoding images with your implementation on an all black image and saw gray pixels randomly come up (they may have been new pixels), to look at an example of how I made it work (probably has some unnecessary code): https://github.com/image-rs/image/compare/main...Murad-Awad:image:upgrade-zune

**Comment by Murad-Awad** [comment]
> You need to use ZCursors rather than Cursor from what I can tell, did some testing and when decoding images with your implementation on an all black image and saw gray pixels randomly come up (they may have been new pixels), to look at an example of how I made it work (probably has some unnecessary code): [main...Murad-Awad:image:upgrade-zune](https://github.com/image-rs/image/compare/main...Murad-Awad:image:upgrade-zune)

I also tested out a version that is functionally the same as yours outside of setting the color + limits params properly (although limits is probably not needed at all given how it is initialized) + using ZCursor: https://github.com/image-rs/image/compare/main...Murad-Awad:image:mawad/keep-testing-zune

**Comment by fintelia** [comment]
@Murad-Awad could you file an issue against the upstream zune-jpeg crate? My understanding is that this version without ZCursor is intended to decode JPEGs properly, so if you are seeing some that get corrupted, they'll want to know

**Comment by Murad-Awad** [comment]
will do!

**Comment by Murad-Awad** [comment]
issue opened here: [v0.5.0-rc0 jpeg decoder does not work when input is a Cursor (rather than a ZCursor)](https://github.com/etemesi254/zune-image/issues/191#top)

**Pull request closed without merging**
