### PR TITLE
Fix loss of brightness in the JPEG encoder

### LINKED ISSUE #1260: Round-tripping JPEGs makes them darker
This happens in image 0.23.5

## Expected
The output JPEGs look like the input JPEGs

## Actual behaviour
The output JPEGs got darker with each round-trip, even with quality 100

## Reproduction steps
```rust
use image::ImageOutputFormat;
use std::{
    fs::File,
    io::{BufWriter, Write},
};

fn main() -> Result<(), anyhow::Error> {
    for i in 1..10 {
        let img = image::open(format!("image{}.jpg", i))?;
        let mut writer = BufWriter::new(File::create(format!("image{}.jpg", i + 1))?);
        img.write_to(&mut writer, ImageOutputFormat::Jpeg(100))?;
        writer.flush()?;
    }

    Ok(())
}
```

image

### PR DESCRIPTION
**Pull request by VVatashi**
Fixes #1260

### CODE REVIEW

**Comment by VVatashi** [comment]
It's just the coefficients from the https://www.w3.org/Graphics/JPEG/jfif.pdf, multiplied by 255, so after dividing by the `max`, they will be exactly the same as there.

**Comment by HeroicKatora** [comment]
That's already good information.

> Coefficients from JPEG File Interchange Format (Version 1.02), multiplied for 255 maximum.

would be a perfectly fine comment

**Comment by HeroicKatora** [comment]
Thanks! Now just waiting on CI :slightly_smiling_face:

**Comment by HeroicKatora** [comment]
:tada:

**Pull request merged**
