### PR TITLE
update openexr 

### PR DESCRIPTION
**Pull request by johannesvollmer**
exr crate license was updated. improves behaviour with cargo-deny.

### CODE REVIEW

**Review by fintelia — APPROVED** [review]
Cargo should automatically use newer minor versions when you run `cargo update` or create a new project, so this update isn't required. At the same time it doesn't hurt anything, so :+1:

**Comment by johannesvollmer** [comment]
Even if the exr dependency is specified exactly? I thought this would only work if we use `1.4` instead of `1.4.2` in cargo toml :)

**Comment by JonasHedEng** [comment]
@johannesvollmer It would be the case if it was specified like `=1.4.2` instead of `1.4.2` :)

**Comment by johannesvollmer** [comment]
Ah yes, I see! Thanks :)

**Comment by johannesvollmer** [comment]
Did you check whether cargo-deny accepts the crate now, with the new license?

**Pull request merged**
