### PR TITLE
Fixed broken build with no default features

### PR DESCRIPTION
**Pull request by bvssvni**
- Bumped to 0.22.1

### CODE REVIEW

**Comment by bvssvni** [comment]
`cargo test --no-default-features` fails because the type of the tuple `(u64, u64)` can not be inferred from the returning error case.

**Comment by bvssvni** [comment]
I bumped the patch version because this is not a breaking change. Looking at the logs, I could not find breaking changes since last published version (0.22.0). Best to double check this, though.

**Comment by HeroicKatora** [comment]
Oh no.. :smile: Can you add a CI test for that one as well? And it should be fine as a minor patch.

**Comment by bvssvni** [comment]
Done.

**Comment by HeroicKatora** [comment]
Published

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
