### PR TITLE
Upgrade tiff to 0.6

### PR DESCRIPTION
**Pull request by HeroicKatora**
I'm not sure if we should forbid the floating point color types `Rgb{,a}{F32,F64}` more explicitly for now but `bytemuck` makes it painless to defined the buffer conversion, even though our own `ColorType` does not support those buffers yet.

### CODE REVIEW

**Review by fintelia — COMMENTED** [review]
Shouldn't the colortype conversion code also have to be updated to handle floats?

**Comment by HeroicKatora** [comment]
We'd need to introduce floating point `ColorType` in the first place, I think. Plus I think the `SampleFormat` is not actually correctly exposed in `tiff`. Good point.

**Comment by HeroicKatora** [comment]
> Shouldn't the colortype conversion code also have to be updated to handle floats?

I'm not even sure how exactly how to do this. I've added checks such that this surely returns an error early for now.

**Comment by HeroicKatora** [comment]
The build failure is:

> thread 'main' panicked at 'This version of NASM is too old: No such file or directory (os error 2)', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rav1e-0.4.0-alpha/build.rs:244:7
>
>  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

We might need to adjust the build to either install `nasm` or to skip it.

**Comment by HeroicKatora** [comment]
Seems like it needs `2.14` but the latest package in the Ubuntu 18.04 environment is `2.11`. I'm going to disable that build for now...

**Comment by paolobarbolini** [comment]
> Seems like it needs 2.14 but the latest package in the Ubuntu 18.04 environment is 2.11. I'm going to disable that build for now...

You can run this on `ubuntu-20.04`

**Comment by HeroicKatora** [comment]
Correction: the image is based on `rust: latest` which is based on Debian buster. So the distribution is not directly in our control unless we bootstrap the Rust installation as well. But the latest package is `nasm: 2.14`. Ah, I just missed updating the package cache first :slightly_smiling_face:

**Comment by HeroicKatora** [comment]
There is a way to run it on 20.04, that is by explicitly setting the distribution to `focal`. This has the required version of `nasm`.

**Pull request merged**
