### PR TITLE
Derive Debug on FilterType

### PR DESCRIPTION
**Pull request by ethanboxx**
This just makes life easier.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I don't see any reason not to.

**Comment by HeroicKatora** [comment]
@ethanboxx Since this is your first contribution, you are invited to the collaborators team with write access to ease further contributions. See [the contribution policy](https://github.com/image-rs/organization/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/image-rs/organization/blob/master/CODE_OF_CONDUCT.md). I can send you an invite if you want.

**Comment by ethanboxx** [comment]
@HeroicKatora Thank you for merging. I have read the contribution policy and code of conduct and would be happy to receive an invite.

**Comment by HeroicKatora** [comment]
Welcome!

**Pull request merged**
