### PR TITLE
Restrict openexr to little endian platforms

### PR DESCRIPTION
**Pull request by HeroicKatora**
Supposed to fix: #1715 

Not certain if this works correctly, at least it appears to not make a difference for little endian architectures. We would do well to test on a big-endian platform in CI in any case.

cc: @botovq

### CODE REVIEW

**Comment by HeroicKatora** [comment]
@johannesvollmer No need to rush anything, but if you have strategies to CI test on big endian then I'd be happy if you could transfer them here.

**Comment by botovq** [comment]
Thanks.

Unfortunately, that doesn't quite work: the default feature list

https://github.com/image-rs/image/blob/0842cce4c743f4c6af4e72dda8b064b0ecd974db/Cargo.toml#L65

enables `feature = openexr`, which attempts to pull in `exr`, which isn't defined on big-endian.

```
error[E0463]: can't find crate for `exr` 314/396: serde, image, tiff, lofty, jpeg-decoder, serd...
  --> /usr/ports/pobj/czkawka-4.1.0/czkawka-4.1.0/modcargo-crates/image-0.24.1/./src/codecs/openexr.rs:24:1
   |
24 | extern crate exr;
   | ^^^^^^^^^^^^^^^^^ can't find crate
```

You can simulate this by flipping the endianness of your `Config.toml` patch:

```
[target.'cfg(target_endian = "big")'.dependencies]
```

I haven't managed to figure out how to enable a feature only for certain target platforms. [This thread](https://github.com/rust-lang/cargo/issues/1197#issuecomment-901794879) seems to suggest that this still isn't possible, but it's long and confusing, so perhaps I'm missing something.


[1]: https://github.com/image-rs/image/blob/0842cce4c743f4c6af4e72dda8b064b0ecd974db/Cargo.toml#L65

**Comment by HeroicKatora** [comment]
Can you try just removing `extern crate exr;`? It shouldn't be required at all.

**Comment by botovq** [comment]
Right. The problem of using an undefined dependency remains:

```
error[E0433]: failed to resolve: use of undeclared crate or module `exr`
  --> /usr/ports/pobj/czkawka-4.1.0/czkawka-4.1.0/modcargo-crates/image-0.24.2/./src/codecs/openexr.rs:24:5
   |
24 | use exr::prelude::*;
   |     ^^^ use of undeclared crate or module `exr`

error[E0433]: failed to resolve: use of undeclared crate or module `exr`
```

**Comment by HeroicKatora** [comment]
Nevermind, I understand what you mean. There are also several other explicit references to the `exr` crate that would be enabled and fail to resolve. I'm looking into a clever way to solve this if we can detect if the actual `exr` feature is available.

**Comment by HeroicKatora** [comment]
@botovq I tried cfg-gating all reference. May have missing some, actually, but could you give it a try?

**Comment by botovq** [comment]
This works. Thank you!

**Review by fintelia — APPROVED** [review]
If this has been tested to both work for users of exr on little endian and compiles properly on big endian, then looks good to me!

**Pull request merged**
