### PR TITLE
Expose in place operations on DynamicImage

### PR DESCRIPTION
**Pull request by Shnatsel**
This is a straightforward pass-through of the existing imageops functions.

### CODE REVIEW

**Comment by ripytide** [comment]
I thought we were removing the image ops functionality to the `imageproc` crate, propagating the `imageops` methods seems to be in conflict with this goal #2238 as they would eventually be deprecated and removed

**Comment by Shnatsel** [comment]
Rotations and flips are required to apply JPEG orientation metadata. We will want reading JPEGs with the correct orientation to "just work" in the future without extra dependencies, so rotations and flips specifically have to stay. 

I agree with removing blur, huerotate, etc.

**Comment by ripytide** [comment]
But is that not the responsibility of the decoding jpeg library and not something we should expose as a public method on the image types in this crate? Especially since none of the rotation or flipping functions are used anywhere within the crate as far as I can see.

**Comment by Shnatsel** [comment]
Exif metadata can also appear on PNG and WebP images. And none of the format decoders actually parse Exif themselves. So it is preferable to implement it once on top of the different decoders, instead of trying to plumb it into each low-level format decoder.

**Comment by ripytide** [comment]
Would you be able to use the flip/rotate functions from the `imageproc` library when they eventually get released?

**Comment by kornelski** [comment]
These days EXIF rotation is de-facto required for decoding of JPEG images the way users expect.

For historical reasons it's a bit overcomplicated, but it can be considered a part of the codec now.

**Review by fintelia — COMMENTED** [review]
I commented [here](https://github.com/image-rs/image/pull/2299#discussion_r1732062083) but I'd actually rather only expose a single rotate-in-place method. The `DynamicImage` type already has so many methods that each additional one we add makes it that much harder for users to find the functionality they're looking for

**Comment by Shnatsel** [comment]
Understood. I'll change the newly added methods to private and add a single function for in-place rotation in #2299. Closing in favor of #2299.

**Pull request closed without merging**
