### PR TITLE
Fix `GifDecoder::with_limits` to raise an error when limits are exceeded

### PR DESCRIPTION
**Pull request by Shnatsel**
Partly addresses #1052

### CODE REVIEW

**Review by fintelia — COMMENTED** [review]
Could you instead reuse the logic from `new`?

```rust
#[deprecated("Use `new` followed by `set_limits` instead")]
pub fn with_limits(r: R, limits: Limits) -> ImageResult<GifDecoder<R>> {
    let mut decoder = Self::new(r)?;
    decoder.set_limits(limits)?;
    Ok(decoder)
}

**Comment by Shnatsel** [comment]
Done. Do you want me to deprecate `with_limits` on `PngDecoder` as well?

**Comment by Shnatsel** [comment]
At a glance, the `PngDecoder` does not seem to implement `set_limits`, so the `with_limits` constructor is the only way to set them reliably. That's probably also something worth fixing, if that's actually true.

**Comment by Shnatsel** [comment]
You know what, let's just merge this as-is since it's a clear fix, and I'll do my own research on the limits across all decoders. I don't want to distract you from the reviews on the `png` crate and your work on WebP.

**Comment by fintelia** [comment]
`PngDecoder` should also be changed. But sadly we can't support `set_limits` there without a breaking change.

The issue is a subtle problem with the type signature of `PngDecoder::is_apng` that doesn't let us return limit or parsing errors. Instead we have to do metadata parsing ahead of time in `new`/`with_limits` so that we can report those errors. But once we've parsed the metadata the crate doesn't let us set the allocation limit (and that's the correct approach because we want to use the limit to avoid allocating an unbounded amount of space for storing metadata!)

**Pull request merged**
