### PR TITLE
chore: Update glob to 0.3

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by HeroicKatora** [comment]
The major version upgrade made this seem like a breaking change. But it's only within `dev-dependencies` so it doesn't matter greatly that it was not included in the release.

Is there any bug or other critical reason for upgrading this?

**Comment by ignatenkobrain** [comment]
Just trying to get rid out of downstream patches in Fedora :)

**Comment by HeroicKatora** [comment]
Ah I see. Not sure if this warrants its own release (what's your preference and opinion?) but it will definitely be in the next one of this version then.

**Comment by ignatenkobrain** [comment]
As long as new version would come out within few months -- I'm okay :)

**Pull request merged**
