### PR TITLE
pcx: Switch test images out

### PR DESCRIPTION
**Pull request by lupine**
The PCX images included in https://github.com/image-rs/image/pull/2364 have dubious licenses. The CGA ones may be  LGPL or GPL (provenance breadcrumb: https://samples.ffmpeg.org/image-samples/pcx/cga/cga-pcx.txt ), while the marbles ones appear to be copyright O'Reilly, with no license grant (https://netghost.narod.ru/gff/sample/images/pcx/index.htm ).

It's worth noting that the tests/ directory is excluded from the crate build, but it's still worth swapping these out for an unambiguously OK image. To do that, I converted the `tests/images/bmp/images/V5_24_Bit.bmp` to a 24-bit PCX file:

```
$ file tests/images/pcx/images/24bit.pcx 
tests/images/pcx/images/24bit.pcx: PCX ver. 3.0 image data bounding box [0, 0] - [434, 352], 3 planes each of 8-bit colour, 72 x 72 dpi, RLE compressed
```

I then downsampled that to a 256-colour paletted image, to exercise both of the code paths we call in the `pcx` crate.

```
$ file tests/images/pcx/images/256-palette.pcx 
tests/images/pcx/images/256-palette.pcx: PCX ver. 3.0 image data bounding box [0, 0] - [434, 352], 8-bit colour, 72 x 72 dpi, RLE compressed
```

cc @HeroicKatora @fintelia

### CODE REVIEW

**Review by kornelski — APPROVED** [review]

**Comment by kornelski** [comment]
@HeroicKatora The PCX supoprt has been merged recently. Maybe rebase+fixup and force-push the main branch to purge the old images from git history?

**Comment by fintelia** [comment]
Feel free to disable the branch protection, force-push a fixup, and then re-enable the protection

**Comment by kornelski** [comment]
I don't have permissions to access settings. I've created https://github.com/image-rs/image/tree/main-rebased branch that you can push

```bash
git push origin -f 9ee68e2afaff118987e953e470cf7221d5f04e71:main
```

**Comment by fintelia** [comment]
Done. Thanks everyone

**Pull request merged**
