### PR TITLE
Document WebP encoder limitations

### PR DESCRIPTION
**Pull request by Shnatsel**
Explain the trade-offs involved and link to example code for encoding with libwebp.

### CODE REVIEW

**Review by HeroicKatora — APPROVED** [review]

**Comment by Shnatsel** [comment]
I see a lot of my PRs are approved but not merged. Does the project have a policy to require approval from several maintainers before merging a PR?

**Comment by HeroicKatora** [comment]
@Shnatsel CI hadn't finished when I pressed it (or Github didn't load). If you can, feel free to press the merge button on good judgment especially with approval there. Also

- [ ] clippy is broken again based on a long doc paragraph
- [ ] `exr` needs the latest version of `miniz_oxide`

Putting up this checklist just so I can communicate (including to myself) when I get around to fixing them.

**Comment by Shnatsel** [comment]
I do not have PR merge permissions on this repo.

**Comment by HeroicKatora** [comment]
Let's fix that as well, you'll want them in the coming months in any case I suppose.

**Comment by fintelia** [comment]
@Shnatsel I just added you to the 'Reviewers' team. That should give you write permissions to all the repositories under the _image-rs_ org

**Comment by Shnatsel** [comment]
Thanks! I'll try not to make too much of a mess :sweat_smile:

**Comment by fintelia** [comment]
Parts of this crate predate not just Rust 1.0, but crates.io itself. It'll always be at least somewhat messy :smile:

**Pull request merged**
