### PR TITLE
Flif decoding support implemented

### LINKED ISSUE #469: Support flif
http://flif.info/

### PR DESCRIPTION
**Pull request by birktj**
This PR adds flif decoding support using the [`flif.rs` crate](https://github.com/dgriffen/flif.rs). Only small problem is that this crate is rust 2018, and thus we can't merge this PR before we update the minimal supported `rustc` version.

This fixes #469

### CODE REVIEW

**Comment by birktj** [comment]
A possible solution to the `rustc` version problem could be to not make the `flif` feature a default feature? And say that `rustc` 1.24.1 is not supported when using this feature.

**Comment by HeroicKatora** [comment]
Seems like a possible solution until the next major version that upgrades compiler requirements. It also makes it clear that the older compiler support is deprecated

**Comment by est31** [comment]
MSRV has been increased to 1.34 in 087b9a6ca66613272651d242eadfc836c68a1ac1 so merging this shouldn't be a problem (after a rebase).

**Comment by Shnatsel** [comment]
I'm not sure this is worth the trouble right now. flif.rs is still very limited and will likely have API breaks as it evolves. Besides, the last activity on flif.rs repository was almost a year ago.

**Comment by fintelia** [comment]
The flif.rs crate hasn't been update since 2019. Going to go ahead and close this

**Comment by Shnatsel** [comment]
FLIF is effectively superseded by the lossless mode of JPEG XL.

**Pull request closed without merging**
