### PR TITLE
Rename fuzzing samples for windows compatibility

### LINKED ISSUE #915: [Meta] Can't clone on Windows.
I cannot clone the master branch from Windows. My git version is: `git version 2.21.0.windows.1`

The output of `git clone` is below. Although there are a lot more error messages in the actual output but I didn't want to clutter the post.

```
Cloning into 'image-new'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 15049 (delta 28), reused 50 (delta 24), pack-reused 14986
Receiving objects: 100% (15049/15049), 15.63 MiB | 4.44 MiB/s, done.
Resolving deltas: 100% (9088/9088), done.
error: unable to create file fuzz-afl/in/pnm/id:000004,sig:06,src:000187,op:havoc,rep:4: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000011,src:000000,op:flip1,pos:3,+cov: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000012,src:000000,op:flip1,pos:4: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000013,src:000000,op:flip1,pos:4: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000016,src:000000,op:flip1,pos:7: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000022,src:000000,op:flip2,pos:5,+cov: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000024,src:000000,op:flip4,pos:1,+cov: Invalid argument
error: unable to create file fuzz-afl/in/pnm/id:000025,src:000000,op:flip4,pos:2,+cov: Invalid argument
```

### PR DESCRIPTION
**Pull request by HeroicKatora**
The command used to rename is also added to the minimization script, to
avoid producing the same issue in future corpus directories and to have
a reference if necessary.

This also adds Windows to Travis, not sure if successfully. [See this blog post](https://blog.travis-ci.com/2018-10-11-windows-early-release) that announces it.

Closes #915

### CODE REVIEW

**Comment by HeroicKatora** [comment]
And this isn't going to help evaluate whether it works, because `travis` will first clone the repo and only then fetch the PR and check it out. Anyone else feeling like giving a slow :clap: ?

**Comment by HeroicKatora** [comment]
@ArturKovacs @LaylConway Can one of you help test this manually?

1. Create an empty directory `image`
2. `cd image && git init`
3. `git remote add origin https://github.com/image-rs/image`
4. `git fetch origin +refs/pull/916/merge:`
5. `git checkout FETCH_HEAD`

Which should give you an initialized working directory where you can execute the usual cargo commands.

**Comment by ArturKovacs** [comment]
Thanks for the quick response on the issue. I obtained this PR using the above describe method and I seemed to be able to get the repo without an issue. I also run `cargo test --features "gif_codec jpeg png_codec pnm tga tiff webp hdr"` which finished with all tests being successful.

**Comment by HeroicKatora** [comment]
Then I'm going to merge it and see if anything pops up. In the worst case, travis builds will fail for the next couple for days but we can always put `windows` in the allowed-to-fail targets (I think).

**Pull request merged**
