### PR TITLE
Properly decode interlaced animated gif frames

### PR DESCRIPTION
**Pull request by kennethuil**
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
> Image comes from http://www.ion.uillinois.edu/resources/tutorials/webdesign/WebGraphicsWorkshop/interlaced.html.

Did you find any kind of license statement for this image?

**Comment by kennethuil** [comment]
> 
> 
> > Image comes from http://www.ion.uillinois.edu/resources/tutorials/webdesign/WebGraphicsWorkshop/interlaced.html.
> 
> Did you find any kind of license statement for this image?

No, but I can convert an image already in the repo and test with that.

**Comment by HeroicKatora** [comment]
Please do. Preferrably a small image such as [this one](https://github.com/image-rs/image/blob/next/tests/images/png/interlaced/basi2c08.png).

**Comment by HeroicKatora** [comment]
Thank you!

**Pull request merged**
