### PR TITLE
describe the pixel enumeration order in the doc comment to avoid confusion

### PR DESCRIPTION
**Pull request by sassman**
- main change is the doc string for the enumerator, because I always get confused about the iteration order is it first rows then columns or the other way around. Maybe that helps other for confused people like me.
- the other stuff is just apply cargo fmt

I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

### CODE REVIEW

**Comment by sassman** [comment]
> Remove the fmt commit, it makes review near impossible.

Are ok with separating formatting and change so that there are 2 commits or generally not interested in the reformatting?

**Comment by HeroicKatora** [comment]
Don't provide the formatting in this PR. We had several discussion on it and it's far too large to do likely in a single PR and without _any_ consideration for refining some of the `rustfmt.toml` settings.

**Comment by sassman** [comment]
@HeroicKatora here you go, it's very tiny and not much.

**Comment by HeroicKatora** [comment]
Thanks :slightly_smiling_face:

**Pull request merged**
