### PR TITLE
Replace assert with proper Unsupported error

### PR DESCRIPTION
**Pull request by FlareFlo**
PR for #2049.

I am not quite sure if this is the correct format for the error message of this kind.

### CODE REVIEW

**Comment by FlareFlo** [comment]
Maybe it should include that the alpha must be in I400 format?

**Comment by fintelia** [comment]
It should be possible to somewhat simplify the error construction. Here's an example from another part of the codebase:
https://github.com/image-rs/image/blob/eb05a39313093bf37b7fb435dffa48f0ad122112/src/codecs/dds.rs#L274-L282

It would be also good to add a few words to the error string explaining what isn't supported. If nothing else, it gives a string for folks to search for to find out where the error is coming from.

**Comment by fintelia** [comment]
Oh, and to clarify `UnsupportedErrorKind::Format` means that the image file format isn't support (like say "AVIF isn't supported at all") whereas `UnsupportedErrorKind::GenericFeature` means that the overall format is supported but some specific feature isn't supported, which is the case here.

**Comment by FlareFlo** [comment]
Cargo build did not warn about that unused import :/

**Comment by fintelia** [comment]
To double check, is I400 required by the AVIF spec or just something our decoder needs?

**Comment by FlareFlo** [comment]
> To double check, is I400 required by the AVIF spec or just something our decoder needs?

I400 is monochrome, which i would assume is the only sensible format for the alpha plane

**Comment by fintelia** [comment]
If other layouts aren't allowed, this should be a DocodingError rather than an UnsupportedError.

**Comment by FlareFlo** [comment]
[The note on the AVIF spec](https://aomediacodec.github.io/av1-avif/v1.1.0.html#auxiliary-images) mentions a 3-component image of sorts?

**Comment by FlareFlo** [comment]
I stumbled upon this assertion after encountering an image with a I420 alpha mask, so there might be more to this.

**Comment by FlareFlo** [comment]
I believe the monochrome mention of 3-components relates to the Y C and B mapping for the alpha layer, meaning that 3 seperate alpha masks could be stored via I444 (or any format for that matter). Its possible the assertion checks against I400 because image only supports one alpha layer?

**Comment by fintelia** [comment]
Thanks!

**Comment by FlareFlo** [comment]
Are there any other formats that have more than one alpha layer?

**Comment by fintelia** [comment]
TIFF and probably EXR support arbitrary numbers of layers. Other than that, I don't think there are other common formats that support multiple alpha layers

**Pull request merged**
